### ISSUE TITLE
Java out of heap space

### ISSUE THREAD

**Issue by Aran30** [rwth-acis/mobsos#2]
After a while, the error "Java out of heap space" pops up in mobsos-success-modeling.

Came up while the service was trying to communicate with the file service (maybe with the file service not being reachable, mobsos-success-modeling stores the files, which creates overhead?).

**Comment by lakhoune** [comment]
@Aran30  did you still encounter this issue?

**Comment by Aran30** [comment]
> 
> 
> @Aran30 did you still encounter this issue?

Well I didn't particularly work on this issue or the mobsos issues in general since you've moved the deployments to the dev network. So no, I did not encounter it anymore, but there was nothing that could have triggered it in the main network I think.

**Comment by AlexanderNeumann** [comment]
Still present in our main network: 
```
Exception in thread "RxCachedThreadScheduler-2" io.reactivex.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | unable to create native thread: possibly out of memory or process/resource limits reached
	at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:69)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.lang.OutOfMemoryError: unable to create native thread: possibly out of memory or process/resource limits reached
	at java.base/java.lang.Thread.start0(Native Method)
	at java.base/java.lang.Thread.start(Thread.java:801)
	at java.base/java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:939)
	at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1356)
	at java.base/java.util.concurrent.CompletableFuture.asyncRunStage(CompletableFuture.java:1814)
	at java.base/java.util.concurrent.CompletableFuture.runAsync(CompletableFuture.java:2023)
	at org.web3j.utils.Async.run(Async.java:33)
	at org.web3j.protocol.Service.sendAsync(Service.java:54)
	at org.web3j.protocol.core.Request.sendAsync(Request.java:85)
	at i5.las2peer.registry.Contracts.getBlockTimestamp(Contracts.java:91)
	at i5.las2peer.registry.BlockchainObserver.lambda$observeETHTransactions$1(BlockchainObserver.java:197)
	at io.reactivex.internal.subscribers.LambdaSubscriber.onNext(LambdaSubscriber.java:65)
	at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.onNext(FlowableSubscribeOn.java:97)
	at io.reactivex.internal.operators.flowable.FlowableObserveOn$ObserveOnSubscriber.runAsync(FlowableObserveOn.java:407)
	at io.reactivex.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.run(FlowableObserveOn.java:176)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)

```
